import './globals.css';

import GlobalModal, {
  GlobalModalProvider,
} from '@/components/common-components/global-modal';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalModalProvider>
          {children}
          <GlobalModal />
        </GlobalModalProvider>
      </body>
    </html>
  );
}
